export const CREATIVE_CATEGORIES = [
  {
    id: 'weddings',
    name: 'Weddings & Engagements',
    slug: 'weddings',
    role: 'photographer',
    icon: 'Heart',
    description: 'Capture authentic emotional moments and grand wedding ceremonies with artistic precision.',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
    count: '240+ Pros',
  },
  {
    id: 'pre-wedding',
    name: 'Cinematic Pre-Wedding',
    slug: 'pre-wedding',
    role: 'videographer',
    icon: 'Video',
    description: 'Story-driven 4K visuals, drone cinematography, and cinematic storytelling reels.',
    image: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&w=800&q=80',
    count: '180+ Pros',
  },
  {
    id: 'corporate-events',
    name: 'Corporate & Summits',
    slug: 'corporate',
    role: 'photographer',
    icon: 'Briefcase',
    description: 'Polished conference coverage, executive portraits, summit recaps, and brand storytelling.',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    count: '130+ Pros',
  },
  {
    id: 'product-commercial',
    name: 'Product & Commercial',
    slug: 'commercial',
    role: 'photographer',
    icon: 'Sparkles',
    description: 'High-conversion e-commerce catalogs, studio lighting, advertising, and 3D product stills.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    count: '95+ Pros',
  },
  {
    id: 'reels-shorts',
    name: 'Reels, TikTok & Shorts Editing',
    slug: 'reels-editing',
    role: 'editor',
    icon: 'Film',
    description: 'Fast-paced hook-driven editing, dynamic subtitles, motion graphics, and sound design.',
    image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=800&q=80',
    count: '310+ Editors',
  },
  {
    id: 'color-grading',
    name: 'Color Grading & Post-Production',
    slug: 'color-grading',
    role: 'editor',
    icon: 'Layers',
    description: 'DaVinci Resolve film emulation, LUT workflows, atmospheric grade, and audio mastering.',
    image: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=800&q=80',
    count: '140+ Editors',
  },
  {
    id: 'birthdays-portraits',
    name: 'Birthdays & Personal Shoots',
    slug: 'personal-shoots',
    role: 'photographer',
    icon: 'Camera',
    description: 'Fashion lookbooks, maternity shoots, family milestones, and birthday celebrations.',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    count: '210+ Pros',
  },
  {
    id: 'music-videos',
    name: 'Music Videos & Documentaries',
    slug: 'music-videos',
    role: 'videographer',
    icon: 'Clapperboard',
    description: 'Music promo videos, narrative shorts, multi-cam live performances, and documentaries.',
    image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80',
    count: '75+ Pros',
  },
];
