import { ROLES } from './roles';

export const MOCK_PROFESSIONALS = [
  {
    id: 'pro-1',
    name: 'Aarav Mehta',
    role: ROLES.PHOTOGRAPHER,
    tagline: 'Fine Art Wedding & Royal Celebration Photographer',
    bio: '10+ years capturing grand Indian weddings and destination celebrations across Udaipur, Goa, and Europe. Featured in Vogue Weddings and WedMeGood.',
    rating: 4.96,
    reviewCount: 128,
    startingPrice: 25000,
    priceUnit: 'per_day',
    location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 10,
    specialties: ['Royal Weddings', 'Pre-Wedding', 'Candid Moments', 'Drone Stills'],
    equipment: ['Sony A7R V (x2)', 'G-Master 24-70mm f/2.8', '85mm f/1.4 GM', 'DJI Mavic 3 Pro', 'Godox AD600 Pro'],
    portfolio: [
      {
        id: 'port-1',
        title: 'Sunset Palace Wedding in Udaipur',
        category: 'Weddings',
        url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-2',
        title: 'Golden Hour Pre-Wedding in Ladakh',
        category: 'Pre-Wedding',
        url: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-3',
        title: 'Candid Bridal Portrait',
        category: 'Portraits',
        url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-4',
        title: 'Sangeet Night Lights & Dance',
        category: 'Events',
        url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-1',
        title: 'Cinematic Pre-Wedding Shoot',
        price: 25000,
        pricingType: 'fixed',
        deliveryDays: 7,
        description: 'Full day on-location shoot at up to 2 scenic locations with outfit styling guidance and 50 color-graded frames.',
        inclusions: ['1 Full Day Shoot', '50 Color Graded High-Res Photos', 'Styling Guidance', 'Social Media Teaser'],
      },
      {
        id: 'srv-2',
        title: 'Full Day Royal Wedding Coverage',
        price: 45000,
        pricingType: 'per_day',
        deliveryDays: 14,
        description: 'Comprehensive 12-hour dual-candid photographer setup, 400+ high-res retouched frames, drone stills, and signature mini album.',
        inclusions: ['2 Master Photographers', 'High-Res Edited Images', 'Drone Stills', 'Teaser Preview in 48 Hours', 'Signature Hardcover Album'],
      },
      {
        id: 'srv-3',
        title: 'Destination 3-Day Wedding Extravaganza',
        price: 85000,
        pricingType: 'per_project',
        deliveryDays: 21,
        description: 'Turnkey 3-day coverage (Mehendi, Sangeet, Wedding, Reception) with 3 photographers and luxury coffee table album.',
        inclusions: ['3 Master Photographers', '800+ Master Graded Images', 'Full Drone Aerials', 'Same-Day Highlights Reel', 'Luxury Italian Leather Album'],
      },
    ],
  },
  {
    id: 'pro-2',
    name: 'Kabir Varma',
    role: ROLES.VIDEOGRAPHER,
    tagline: 'Cinematic Film Director & 4K/8K Cinema DP',
    bio: 'Directing high-octane brand films, music videos, luxury real estate tours, and breathtaking cinematic wedding films. RED and FX6 cinema camera specialist.',
    rating: 4.98,
    reviewCount: 94,
    startingPrice: 35000,
    priceUnit: 'per_day',
    location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 8,
    specialties: ['Cinematic Wedding Films', 'Commercial Ads', 'Music Videos', 'FPV & Drone Cinema'],
    equipment: ['Sony FX6 Cinema Line', 'Sony FX3 B-Cam', 'DJI Inspire 3 Drone', 'Sennheiser Wireless Mics', 'Aputure 600d Pro Lighting'],
    portfolio: [
      {
        id: 'port-5',
        title: 'Echoes of Love — Destination Wedding Film',
        category: 'Films',
        url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
        mediaType: 'video',
      },
      {
        id: 'port-6',
        title: 'Hyper-Car Commercial Launch',
        category: 'Commercial',
        url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
        mediaType: 'video',
      },
    ],
    services: [
      {
        id: 'srv-4',
        title: 'Commercial Brand Film (Single Day)',
        price: 35000,
        pricingType: 'per_day',
        deliveryDays: 10,
        description: 'Single-day commercial filming with Sony FX6 rig, professional lighting grid, and licensed music score.',
        inclusions: ['60-Sec High-Conversion Ad', '15-Sec Social Cutdown', 'Professional Voiceover Sync', '4K Master Delivery'],
      },
      {
        id: 'srv-5',
        title: 'Cinematic Wedding Teaser & Film (4K)',
        price: 55000,
        pricingType: 'fixed',
        deliveryDays: 20,
        description: 'Multi-camera 4K cinematography with drone sweeps, professional sound recording, and master color grading.',
        inclusions: ['4-5 Min Cinematic Teaser', '25 Min Extended Film', 'Raw Footage Hard Drive', 'Licensed Soundtracks'],
      },
      {
        id: 'srv-6',
        title: 'Grand 8K Feature Documentary Production',
        price: 95000,
        pricingType: 'per_project',
        deliveryDays: 30,
        description: 'Full multi-day cinematic production with dual DP cinema rigs, FPV aerial pilot, sound engineer, and theatrical master export.',
        inclusions: ['Dual FX6 Cinema Operators', 'Licensed FPV Drone Pilot', 'Full Length 45-Min Film', '4K Teaser in 72h', 'ProRes 4444 Master Drive'],
      },
    ],
  },
  {
    id: 'pro-3',
    name: 'Sanya Kapoor',
    role: ROLES.EDITOR,
    tagline: 'Lead Colorist & Viral Short-Form Video Specialist',
    bio: 'Edited for top YouTube creators (2M+ subs), Spotify campaign reels, and film festival entries. DaVinci Resolve Studio Certified & Premiere Pro Master.',
    rating: 4.95,
    reviewCount: 165,
    startingPrice: 3500,
    priceUnit: 'per_video',
    location: { city: 'New Delhi', state: 'Delhi', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 6,
    specialties: ['Viral Reels & Shorts', 'DaVinci Color Grading', 'Motion Graphic Titles', 'Sound Design & SFX'],
    equipment: ['Mac Studio M2 Ultra 64GB', 'LG OLED Color Reference Monitor', 'DaVinci Speed Editor Console', 'Studio Monitors'],
    portfolio: [
      {
        id: 'port-7',
        title: 'Fashion Week Behind The Scenes Reel',
        category: 'Reels',
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        mediaType: 'video',
      },
      {
        id: 'port-8',
        title: 'Film Look Color Grade Showcase',
        category: 'Color Grading',
        url: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-7',
        title: 'Single High-Retention Viral Reel / Short',
        price: 3500,
        pricingType: 'per_video',
        deliveryDays: 2,
        description: 'Pacing optimization, dynamic kinetic typography, SFX soundscapes, and color polish.',
        inclusions: ['1 Viral 9:16 Reel', 'Dynamic Subtitles', 'Sound Effects Library', '24–48h Turnaround'],
      },
      {
        id: 'srv-8',
        title: 'Pack of 5 Viral Instagram Reels / TikToks',
        price: 12000,
        pricingType: 'fixed',
        deliveryDays: 4,
        description: 'Hook optimization, dynamic text animations, zoom transitions, B-roll integration, and audio soundscaping.',
        inclusions: ['5 High-Retention Short Videos', 'Dynamic Captions', '2 Free Revisions/Video', 'Fast 72h Turnaround'],
      },
      {
        id: 'srv-9',
        title: 'Master Film / Music Video DaVinci Color Grade',
        price: 24000,
        pricingType: 'per_project',
        deliveryDays: 6,
        description: 'DaVinci Resolve node workflow, shot matching, skin tone preservation, custom film emulation LUT delivery.',
        inclusions: ['Rec.709 & HDR Master Deliverables', 'Shot-to-Shot Color Match', 'Film Grain & Halation Effect', 'XML Roundtrip'],
      },
    ],
  },
  {
    id: 'pro-4',
    name: 'Rohan Deshmukh',
    role: ROLES.PHOTOGRAPHER,
    tagline: 'High-End Product, Food & Architecture Photographer',
    bio: 'Specializing in commercial brand aesthetics, studio tabletop photography, architectural marvels, and luxury dining menus.',
    rating: 4.92,
    reviewCount: 78,
    startingPrice: 18000,
    priceUnit: 'per_day',
    location: { city: 'Pune', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 7,
    specialties: ['Product Commercials', 'E-Commerce Stills', 'Architectural Interiors', 'Food Styling'],
    equipment: ['Canon EOS R5', 'Canon RF 100mm Macro f/2.8', 'Profoto B10X Plus Strobes'],
    portfolio: [
      {
        id: 'port-9',
        title: 'Luxury Chronograph Tabletop Stills',
        category: 'Commercial',
        url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-10',
        title: 'E-Commerce Tabletop Catalog (10 Products)',
        price: 18000,
        pricingType: 'fixed',
        deliveryDays: 5,
        description: 'Clean white/grey background catalog stills with specular gradient lighting and dust removal retouching.',
        inclusions: ['30 Finished High-Res Images', 'Multi-Angle Views', 'Amazon/Shopify Optimized', 'Commercial Usage Rights'],
      },
      {
        id: 'srv-11',
        title: 'Architectural Interior & Villa Stills',
        price: 32000,
        pricingType: 'per_day',
        deliveryDays: 7,
        description: 'HDR exposure bracketing, tilt-shift perspectives, twilight golden hour architectural captures.',
        inclusions: ['Full Day On-Location', '40 Retouched Architecture Stills', 'Interior Lighting Setup', 'Print-Ready Files'],
      },
      {
        id: 'srv-12',
        title: 'Full Creative Brand Campaign (30 Assets)',
        price: 50000,
        pricingType: 'per_project',
        deliveryDays: 10,
        description: 'Complete lifestyle prop styling, model integration, high-end macro details, and marketing deliverables.',
        inclusions: ['Creative Director & Prop Stylist', '60 Retouched Hero Stills', 'Raw Files Archive', 'Full Global Buyout Rights'],
      },
    ],
  },
  {
    id: 'pro-5',
    name: 'Tara Sen',
    role: ROLES.PHOTOGRAPHER,
    tagline: 'High-Fashion Editorial & Celebrity Portraitist',
    bio: 'Shooting for luxury fashion houses, model agency portfolios, and international magazine covers across Mumbai & London.',
    rating: 4.97,
    reviewCount: 112,
    startingPrice: 15000,
    priceUnit: 'per_shoot',
    location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 9,
    specialties: ['High Fashion', 'Celebrity Portraits', 'Agency Model Books', 'Editorial Lookbooks'],
    equipment: ['Hasselblad 907X 50C', 'Broncolor Siros 800 L Lights', '80mm f/2.8 Prime'],
    portfolio: [
      {
        id: 'port-10',
        title: 'Editorial Runway Capsule Lookbook',
        category: 'Portraits',
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-13',
        title: 'Editorial Portrait / Model Portfolio (2 Looks)',
        price: 15000,
        pricingType: 'fixed',
        deliveryDays: 4,
        description: 'Studio session with 2 outfit changes, mood lighting, and 15 magazine-grade retouched portraits.',
        inclusions: ['3-Hour Studio Time', '15 High-End Retouched Stills', 'Online Gallery', 'Personal Usage Rights'],
      },
      {
        id: 'srv-14',
        title: 'Fashion Lookbook Campaign (5 Looks)',
        price: 35000,
        pricingType: 'per_day',
        deliveryDays: 8,
        description: 'Full day studio/location production with styling assistance and 40 master graded campaign assets.',
        inclusions: ['Full Day Shoot', '40 Retouched Editorial Stills', 'Model Direction', 'Lookbook PDF Catalog'],
      },
      {
        id: 'srv-15',
        title: 'Magazine Cover Story & Exclusive Campaign',
        price: 60000,
        pricingType: 'per_project',
        deliveryDays: 12,
        description: 'Hasselblad medium format master capture with on-set digital tech, high-end beauty retouching, and full commercial buyout.',
        inclusions: ['Medium Format 50MP Capture', 'On-Set Digital Tech Screen', '80 Master Retouched Frames', 'Full Commercial Buyout'],
      },
    ],
  },
  {
    id: 'pro-6',
    name: 'Dev Malhotra',
    role: ROLES.VIDEOGRAPHER,
    tagline: 'FPV Action Pilot & Aerial Cinematographer',
    bio: 'DGCA-certified drone pilot capturing adrenaline-fueled motorsports, luxury property sweeps, and blockbuster movie drone plates.',
    rating: 4.94,
    reviewCount: 65,
    startingPrice: 20000,
    priceUnit: 'per_day',
    location: { city: 'Goa', state: 'Goa', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 5,
    specialties: ['FPV Action Drones', 'Real Estate Sweeps', 'Outdoor Expeditions', '4K Aerial Cinema'],
    equipment: ['Custom 6S FPV Drone (GoPro 12 Bones)', 'DJI Inspire 3 X9-8K Air', 'RED Komodo Drone Rig'],
    portfolio: [],
    services: [
      {
        id: 'srv-16',
        title: 'Single-Location FPV Property / Action Flight',
        price: 20000,
        pricingType: 'fixed',
        deliveryDays: 3,
        description: 'High-speed one-take indoor/outdoor continuous FPV flight through architectural spaces or action events.',
        inclusions: ['4-Hour Flight Session', '4K 60FPS Stabilized Video', 'Color Graded One-Take Cut', 'Licensed Insurance'],
      },
      {
        id: 'srv-17',
        title: 'Full Day Commercial Aerial Production',
        price: 38000,
        pricingType: 'per_day',
        deliveryDays: 6,
        description: 'DJI Inspire 3 multi-battery flight session with ProRes RAW capture and dual operator control.',
        inclusions: ['Full Day Aerial Operations', '8K Cinema DNG / ProRes RAW', 'Spotter & Safety Crew', 'Raw Media Handoff'],
      },
    ],
  },
];

export const MOCK_BOOKINGS = [
  {
    id: 'bkg-101',
    bookingReference: 'LC-2025-A89F',
    professional: {
      id: 'pro-1',
      name: 'Aarav Mehta',
      role: ROLES.PHOTOGRAPHER,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    },
    user: {
      id: 'usr-1',
      name: 'Pooja Sharma',
      email: 'pooja.sharma@example.com',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    },
    service: {
      title: 'Full Day Royal Wedding Coverage',
      price: 45000,
    },
    eventType: 'Wedding Ceremony',
    eventDate: '2025-11-15',
    city: 'Jaipur, Rajasthan',
    status: 'accepted',
    paymentStatus: 'advance_paid',
    totalAmount: 45000,
  },
  {
    id: 'bkg-102',
    bookingReference: 'LC-2025-B42C',
    professional: {
      id: 'pro-2',
      name: 'Kabir Varma',
      role: ROLES.VIDEOGRAPHER,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    },
    user: {
      id: 'usr-1',
      name: 'Pooja Sharma',
      email: 'pooja.sharma@example.com',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    },
    service: {
      title: 'Cinematic Wedding Teaser & Film (4K)',
      price: 55000,
    },
    eventType: 'Pre-Wedding Shoot',
    eventDate: '2025-10-20',
    city: 'Goa',
    status: 'pending',
    paymentStatus: 'unpaid',
    totalAmount: 55000,
  },
];

export const MOCK_REVIEWS = [
  {
    id: 'rev-1',
    creatorId: 'pro-1',
    creatorName: 'Aarav Mehta',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    clientName: 'Pooja & Rohan',
    clientAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    rating: 5,
    date: '2025-06-15',
    event: 'Udaipur Palace Wedding',
    comment: 'Aarav and his team were absolutely phenomenal at our Udaipur wedding. Every photograph looks like high fashion.',
  },
  {
    id: 'rev-2',
    creatorId: 'pro-2',
    creatorName: 'Kabir Varma',
    creatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    clientName: 'Vikram Sethi',
    clientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    rating: 5,
    date: '2025-05-20',
    event: 'Goa Sunset Cinematography',
    comment: 'The 4K cinematic film brought tears to our eyes. Masterful sound design, grading, and drone shots.',
  },
  {
    id: 'rev-3',
    creatorId: 'pro-3',
    creatorName: 'Sanya Kapoor',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    clientName: 'StyleCo Luxury',
    clientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    rating: 5,
    date: '2025-04-10',
    event: 'Fashion Week Campaign',
    comment: 'Sanya turned around 5 viral reels in 48 hours. Our engagement spiked 300% on Instagram.',
  },
];

export const MOCK_STATS = {
  admin: {
    totalUsers: 1420,
    totalProfessionals: 380,
    photographers: 195,
    videographers: 110,
    editors: 75,
    totalBookings: 890,
    totalRevenue: 2845000,
    activeDisputes: 2,
  },
  professional: {
    totalEarnings: 385000,
    thisMonthEarnings: 75000,
    activeBookings: 6,
    completedProjects: 42,
    clientSatisfaction: '99.4%',
    profileViews: 1840,
  },
  user: {
    activeBookingsCount: 2,
    completedBookingsCount: 8,
    savedProsCount: 14,
    reviewsGivenCount: 5,
  },
};
