import { ROLES } from './roles';

export const MOCK_PROFESSIONALS = [
  {
    id: 'pro-1',
    name: 'Aarav Mehta',
    role: ROLES.PHOTOGRAPHER,
    tagline: 'Fine Art Wedding & Editorial Portrait Photographer',
    bio: '10+ years capturing grand Indian weddings and destination celebrations across Udaipur, Goa, and Europe. Featured in Vogue Weddings and WedMeGood.',
    rating: 4.96,
    reviewCount: 128,
    startingPrice: 25000,
    priceUnit: 'per_day',
    location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 10,
    specialties: ['Royal Weddings', 'Pre-Wedding', 'Candid Moments', 'Drone Photography'],
    equipment: ['Sony A7R V (x2)', 'G-Master 24-70mm f/2.8', '85mm f/1.4 GM', 'DJI Mavic 3 Pro', 'Godox AD600 Pro'],
    portfolio: [
      {
        id: 'port-1',
        title: 'Sunset Palace Wedding in Udaipur',
        category: 'Weddings',
        url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-2',
        title: 'Golden Hour Pre-Wedding in Ladakh',
        category: 'Pre-Wedding',
        url: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-3',
        title: 'Candid Bridal Portrait',
        category: 'Portraits',
        url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-4',
        title: 'Sangeet Night Lights & Dance',
        category: 'Events',
        url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-1',
        title: 'Full Day Royal Wedding Coverage',
        price: 45000,
        pricingType: 'per_day',
        deliveryDays: 14,
        description: 'Comprehensive 12-hour dual-candid photographer setup, 400+ high-res retouched frames, drone stills, and signature mini photo album.',
        inclusions: ['2 Master Photographers', 'High-Res Edited Images', 'Drone Stills', 'Teaser Preview in 48 Hours', 'Signature Hardcover Album'],
      },
      {
        id: 'srv-2',
        title: 'Cinematic Pre-Wedding Shoot',
        price: 25000,
        pricingType: 'fixed',
        deliveryDays: 7,
        description: '1 Full day shoot at up to 2 locations with outfit changes and creative mood-board direction.',
        inclusions: ['Full Day Shoot', '50 Color Graded High-Res Photos', 'Styling Guidance', 'Social Media Teaser'],
      },
    ],
  },
  {
    id: 'pro-2',
    name: 'Kabir Varma',
    role: ROLES.VIDEOGRAPHER,
    tagline: 'Cinematic Film Director & Commercial DP',
    bio: 'Directing high-octane brand films, music videos, luxury real estate tours, and breathtaking cinematic wedding films. RED and FX3 cinema camera specialist.',
    rating: 4.98,
    reviewCount: 94,
    startingPrice: 35000,
    priceUnit: 'per_day',
    location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 8,
    specialties: ['Cinematic Wedding Films', 'Commercial Ads', 'Music Videos', 'FPV & Drone Cinema'],
    equipment: ['Sony FX6 Cinema Line', 'Sony FX3 B-Cam', 'DJI Inspire 3 Drone', 'Sennheiser Wireless Mics', 'Aputure 600d Pro Lighting'],
    portfolio: [
      {
        id: 'port-5',
        title: 'Echoes of Love — Destination Wedding Film',
        category: 'Films',
        url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
        mediaType: 'video',
      },
      {
        id: 'port-6',
        title: 'Hyper-Car Commercial Launch',
        category: 'Commercial',
        url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
        mediaType: 'video',
      },
    ],
    services: [
      {
        id: 'srv-3',
        title: 'Cinematic Wedding Teaser & Film (4K)',
        price: 55000,
        pricingType: 'fixed',
        deliveryDays: 20,
        description: 'Multi-camera 4K cinematography with drone sweeps, professional sound recording, and master color grading.',
        inclusions: ['4-5 Min Cinematic Teaser', '25 Min Extended Film', 'Raw Footage Hard Drive', 'Licensed Soundtracks'],
      },
    ],
  },
  {
    id: 'pro-3',
    name: 'Sanya Kapoor',
    role: ROLES.EDITOR,
    tagline: 'Lead Colorist & Viral Short-Form Video Specialist',
    bio: 'Edited for top YouTube creators (2M+ subs), Spotify campaign reels, and film festival entries. DaVinci Resolve Studio Certified & Premiere Pro Master.',
    rating: 4.95,
    reviewCount: 165,
    startingPrice: 3500,
    priceUnit: 'per_video',
    location: { city: 'New Delhi', state: 'Delhi', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 6,
    specialties: ['Viral Reels & Shorts', 'DaVinci Color Grading', 'Motion Graphic Titles', 'Sound Design & SFX'],
    equipment: ['Mac Studio M2 Ultra 64GB', 'LG OLED Color Reference Monitor', 'DaVinci Speed Editor Console', 'Studio Monitors'],
    portfolio: [
      {
        id: 'port-7',
        title: 'Fashion Week Behind The Scenes Reel',
        category: 'Reels',
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        mediaType: 'video',
      },
      {
        id: 'port-8',
        title: 'Film Look Color Grade Showcase',
        category: 'Color Grading',
        url: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-4',
        title: 'Pack of 5 Viral Instagram Reels / TikToks',
        price: 12000,
        pricingType: 'fixed',
        deliveryDays: 3,
        description: 'Hook optimization, dynamic text animations, zoom transitions, B-roll integration, and audio soundscaping.',
        inclusions: ['5 High-Retention Short Videos', 'Dynamic Captions', '2 Free Revisions/Video', 'Fast 72h Turnaround'],
      },
      {
        id: 'srv-5',
        title: 'Master Film Color Grading (Per Project)',
        price: 18000,
        pricingType: 'per_project',
        deliveryDays: 5,
        description: 'DaVinci Resolve node workflow, shot matching, skin tone preservation, custom LUT delivery.',
        inclusions: ['Rec.709 & HDR Master Deliverables', 'Shot-to-Shot Color Match', 'Film Grain & Halation Effect'],
      },
    ],
  },
  {
    id: 'pro-4',
    name: 'Rohan Deshmukh',
    role: ROLES.PHOTOGRAPHER,
    tagline: 'High-End Product, Food & Architecture Photographer',
    bio: 'Specializing in commercial brand aesthetics, studio tabletop photography, architectural marvels, and luxury dining menus.',
    rating: 4.92,
    reviewCount: 78,
    startingPrice: 18000,
    priceUnit: 'per_day',
    location: { city: 'Pune', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 7,
    specialties: ['Product Commercials', 'E-Commerce Stills', 'Architectural Interiors', 'Food Styling'],
    equipment: ['Canon EOS R5', 'Canon RF 100mm Macro f/2.8', 'Profoto B10X Plus Strobes'],
    portfolio: [],
    services: [],
  },
];

export const MOCK_BOOKINGS = [
  {
    id: 'bkg-101',
    bookingReference: 'LC-2025-A89F',
    professional: {
      id: 'pro-1',
      name: 'Aarav Mehta',
      role: ROLES.PHOTOGRAPHER,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    },
    user: {
      id: 'usr-1',
      name: 'Pooja Sharma',
      email: 'pooja.sharma@example.com',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    },
    service: {
      title: 'Full Day Royal Wedding Coverage',
      price: 45000,
    },
    eventType: 'Wedding Ceremony',
    eventDate: '2025-11-15',
    city: 'Jaipur, Rajasthan',
    status: 'accepted',
    paymentStatus: 'advance_paid',
    totalAmount: 45000,
  },
  {
    id: 'bkg-102',
    bookingReference: 'LC-2025-B42C',
    professional: {
      id: 'pro-2',
      name: 'Kabir Varma',
      role: ROLES.VIDEOGRAPHER,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    },
    user: {
      id: 'usr-1',
      name: 'Pooja Sharma',
      email: 'pooja.sharma@example.com',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    },
    service: {
      title: 'Cinematic Wedding Teaser & Film (4K)',
      price: 55000,
    },
    eventType: 'Pre-Wedding Shoot',
    eventDate: '2025-10-20',
    city: 'Goa',
    status: 'pending',
    paymentStatus: 'unpaid',
    totalAmount: 55000,
  },
];

export const MOCK_STATS = {
  admin: {
    totalUsers: 1420,
    totalProfessionals: 380,
    photographers: 195,
    videographers: 110,
    editors: 75,
    totalBookings: 890,
    totalRevenue: 2845000,
    activeDisputes: 2,
  },
  professional: {
    totalEarnings: 385000,
    thisMonthEarnings: 75000,
    activeBookings: 6,
    completedProjects: 42,
    clientSatisfaction: '99.4%',
    profileViews: 1840,
  },
  user: {
    activeBookingsCount: 2,
    completedBookingsCount: 8,
    savedProsCount: 14,
    reviewsGivenCount: 5,
  },
};
