import { ROLES } from './roles';

export const MOCK_PROFESSIONALS = [
  {
    id: 'pro-1',
    name: 'Aarav Mehta',
    role: ROLES.PHOTOGRAPHER,
    category: 'Royal Wedding Photographer',
    tagline: 'Fine Art Wedding & Royal Celebration Photographer',
    bio: '10+ years capturing grand Indian royal weddings and destination celebrations across Udaipur, Goa, Florence, and Lake Como. Featured in Vogue Weddings, Harper’s Bazaar Bride, and WedMeGood.',
    rating: 4.98,
    reviewCount: 142,
    completedShoots: 185,
    startingPrice: 35000,
    priceUnit: 'per_day',
    location: { city: 'Mumbai / Udaipur', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 10,
    specialties: ['Royal Weddings', 'Pre-Wedding', 'Candid Moments', 'Drone Stills'],
    equipment: ['Sony A7R V (x2)', 'Sony G-Master 24-70mm f/2.8 II', '85mm f/1.4 GM', 'DJI Mavic 3 Pro Cine', 'Godox AD600 Pro Strobes'],
    portfolio: [
      {
        id: 'port-1',
        title: 'Sunset Nuptials at Lake Palace Udaipur',
        category: 'Weddings',
        url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-2',
        title: 'Golden Hour Pre-Wedding in Nubra Valley',
        category: 'Pre-Wedding',
        url: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-3',
        title: 'Candid Royal Bridal Portrait in Sabyasachi',
        category: 'Portraits',
        url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-4',
        title: 'Sangeet Night Lights & Grand Dance',
        category: 'Events',
        url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-1',
        title: 'Cinematic Pre-Wedding Shoot',
        price: 35000,
        pricingType: 'fixed',
        deliveryDays: 7,
        description: 'Full day on-location shoot at up to 2 scenic locations with outfit styling guidance and 60 color-graded frames.',
        inclusions: ['1 Full Day Shoot', '60 Color Graded High-Res Photos', 'Styling Guidance', '48-Hour Teaser Preview'],
      },
      {
        id: 'srv-2',
        title: 'Full Day Royal Wedding Coverage',
        price: 55000,
        pricingType: 'per_day',
        deliveryDays: 14,
        description: 'Comprehensive 12-hour dual-candid photographer setup, 400+ high-res retouched frames, drone stills, and signature mini album.',
        inclusions: ['2 Master Photographers', 'High-Res Edited Images', 'Drone Stills', 'Teaser Preview in 48 Hours', 'Signature Hardcover Album'],
      },
      {
        id: 'srv-3',
        title: 'Destination 3-Day Wedding Extravaganza',
        price: 95000,
        pricingType: 'per_project',
        deliveryDays: 21,
        description: 'Turnkey 3-day coverage (Mehendi, Sangeet, Wedding, Reception) with 3 photographers and luxury coffee table album.',
        inclusions: ['3 Master Photographers', '800+ Master Graded Images', 'Full Drone Aerials', 'Same-Day Highlights Reel', 'Luxury Italian Leather Album'],
      },
    ],
  },
  {
    id: 'pro-2',
    name: 'Kabir Varma',
    role: ROLES.VIDEOGRAPHER,
    category: 'Cinematographer & Film Director',
    tagline: 'Cinematic Film Director & 4K/8K Cinema DP',
    bio: 'Directing high-octane brand films, music videos, luxury real estate tours, and breathtaking cinematic wedding films. RED and FX6 cinema camera specialist with international broadcast credits.',
    rating: 4.97,
    reviewCount: 98,
    completedShoots: 140,
    startingPrice: 42000,
    priceUnit: 'per_day',
    location: { city: 'Bengaluru / Manali', state: 'Karnataka', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 8,
    specialties: ['Cinematic Wedding Films', 'Commercial Ads', 'Music Videos', 'FPV & Drone Cinema'],
    equipment: ['Sony FX6 Cinema Line', 'Sony FX3 B-Cam', 'DJI Inspire 3 Drone', 'Sennheiser Wireless Mics', 'Aputure 600d Pro Lighting'],
    portfolio: [
      {
        id: 'port-5',
        title: 'Himalayan Expedition Documentary 4K',
        category: 'Travel',
        url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-6',
        title: 'Bespoke Luxury Watch Brand Commercial',
        category: 'Commercial',
        url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-4',
        title: 'Brand Commercial & Digital Ad (4K)',
        price: 42000,
        pricingType: 'per_project',
        deliveryDays: 10,
        description: 'Complete 30s + 60s brand commercial production with cinema camera, sound design, and color grading.',
        inclusions: ['1 Day Production', '4K Master Video File', 'Sound Design & Licensing', '3 Aspect Ratios (16:9, 9:16, 1:1)'],
      },
      {
        id: 'srv-5',
        title: 'Cinematic Wedding Film (Full Coverage)',
        price: 65000,
        pricingType: 'per_day',
        deliveryDays: 20,
        description: '3-camera 4K cinema setup, drone aerial cinematography, dialogue recording, 3-5 min teaser + 20-min feature film.',
        inclusions: ['2 Cinematographers + 1 Drone Pilot', '3-5 Min Teaser', '20-Min Highlight Film', 'Full Raw Footage SSD'],
      },
    ],
  },
  {
    id: 'pro-3',
    name: 'Nisha Singhania',
    role: ROLES.PHOTOGRAPHER,
    category: 'High-Fashion & Editorial',
    tagline: 'High-Fashion, Editorial & Celebrity Portraiture',
    bio: 'Shooting lookbooks, runway campaigns, and high-fashion editorials. Work published in Vogue India, GQ, Elle, and Grazia. Hasselblad medium format precision.',
    rating: 4.95,
    reviewCount: 165,
    completedShoots: 210,
    startingPrice: 38000,
    priceUnit: 'per_day',
    location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 9,
    specialties: ['Fashion Lookbooks', 'Celebrity Portraits', 'Jewelry & Couture', 'Studio Chiaroscuro'],
    equipment: ['Hasselblad X2D 100C', 'Profoto B10X Plus (x4)', 'Broncolor Para 133', 'Capture One Pro 23'],
    portfolio: [
      {
        id: 'port-7',
        title: 'Haute Couture Monochrome Studio Campaign',
        category: 'Fashion',
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
      {
        id: 'port-8',
        title: 'Heritage Polki Diamond Jewelry Spread',
        category: 'Commercial',
        url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-6',
        title: 'Editorial Fashion Campaign Lookbook',
        price: 38000,
        pricingType: 'per_day',
        deliveryDays: 7,
        description: 'Up to 6 outfit looks in studio or location, tethered live preview, high-end magazine color grade.',
        inclusions: ['Studio Lighting Setup', 'Tethered Live Preview', '30 Retouched High-Res Images', 'Commercial License'],
      },
    ],
  },
  {
    id: 'pro-4',
    name: 'Devansh Kapoor',
    role: ROLES.EDITOR,
    category: 'DaVinci Resolve Master Colorist',
    tagline: 'Hollywood-Standard DaVinci Resolve Colorist & Film Editor',
    bio: 'Master colorist and post-production supervisor. Graded feature films, Netflix documentaries, international brand commercials, and luxury wedding films.',
    rating: 4.99,
    reviewCount: 240,
    completedShoots: 320,
    startingPrice: 22000,
    priceUnit: 'per_project',
    location: { city: 'Delhi NCR', state: 'Delhi', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1574717024453-354056aafa98?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 11,
    specialties: ['Film Emulation LUTs', 'Commercial Color Grading', 'Wedding Teasers', 'Sound Mixing'],
    equipment: ['DaVinci Resolve Studio & Mini Panel', 'Eizo ColorEdge CG319X Calibrated Display', 'Mac Studio M2 Ultra', 'Flanders Scientific Monitor'],
    portfolio: [
      {
        id: 'port-9',
        title: 'Kodak 5219 35mm Film Grade for Cinema',
        category: 'Color Grading',
        url: 'https://images.unsplash.com/photo-1574717024453-354056aafa98?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-7',
        title: 'Commercial / Music Video 4K Color Grade',
        price: 22000,
        pricingType: 'per_project',
        deliveryDays: 4,
        description: 'Complete shot-matching, skin tone isolation, film grain integration, and master ProRes 4444 delivery.',
        inclusions: ['Color Palette Moodboard', 'Shot-to-Shot Matching', 'Skin Tone Cleanup', '2 Revision Cycles', 'ProRes Masters'],
      },
    ],
  },
  {
    id: 'pro-5',
    name: 'Rohan Deshmukh',
    role: ROLES.PHOTOGRAPHER,
    category: 'Automobile & Product Photographer',
    tagline: 'Automobile, Tech & Precision Studio Commercial Photographer',
    bio: 'Crafting crisp, hyper-detailed automotive campaigns and consumer technology hero images. Client roster includes BMW, Mercedes-Benz India, and Nothing Tech.',
    rating: 4.94,
    reviewCount: 88,
    completedShoots: 160,
    startingPrice: 48000,
    priceUnit: 'per_day',
    location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 7,
    specialties: ['Automotive Rigs', 'Light Painting', 'Macro Watches', 'Commercial Stills'],
    equipment: ['Canon EOS R5 C', 'Broncolor Scoro 3200 RFS 2', '24mm Tilt-Shift', 'Carbon Fiber Rig System'],
    portfolio: [
      {
        id: 'port-10',
        title: 'Dusk Sports Car Light Painting Campaign',
        category: 'Automotive',
        url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-8',
        title: 'Automotive & Product Commercial Shoot',
        price: 48000,
        pricingType: 'per_day',
        deliveryDays: 7,
        description: 'Full day track or studio shoot with custom lighting rigs and master compositing.',
        inclusions: ['Full Studio/Track Lighting', 'Dynamic Motion Rig Stills', '20 Master Retouched Frames', 'Full Commercial Rights'],
      },
    ],
  },
  {
    id: 'pro-6',
    name: 'Ananya Iyer',
    role: ROLES.PHOTOGRAPHER,
    category: 'Bridal Candid & Heritage Wedding',
    tagline: 'Fine Art Candid Bridal & Heritage South Indian Wedding Specialist',
    bio: 'Capturing the deep emotion, gold temple architecture, and soulful rituals of South Indian and destination weddings. Leica and Sony prime lens purist.',
    rating: 4.98,
    reviewCount: 175,
    completedShoots: 195,
    startingPrice: 32000,
    priceUnit: 'per_day',
    location: { city: 'Chennai / Hyderabad', state: 'Tamil Nadu', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 8,
    specialties: ['Temple Weddings', 'Candid Bridal', 'Pre-Wedding Traditions', 'Natural Light Portraits'],
    equipment: ['Leica Q3', 'Sony A1', '50mm f/1.2 GM', '35mm f/1.4 GM', 'Godox V1 Flashes'],
    portfolio: [
      {
        id: 'port-11',
        title: 'Traditional Kanjeevaram Saree Wedding Rituals',
        category: 'Weddings',
        url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-9',
        title: 'Heritage Wedding Candid Coverage',
        price: 32000,
        pricingType: 'per_day',
        deliveryDays: 10,
        description: 'Pure candid coverage capturing laughter, tears, and intricate temple traditions.',
        inclusions: ['1 Lead Candid Artist + 1 Assistant', '300+ Edited Stills', 'Web Gallery', 'Handmade Album Option'],
      },
    ],
  },
  {
    id: 'pro-7',
    name: 'Vikramaditya Roy',
    role: ROLES.VIDEOGRAPHER,
    category: 'Cinema DP & Music Video Director',
    tagline: '8K Cinema DP & High-Octane Music Video / Concert Director',
    bio: 'Director of Photography for mainstream Indian music videos, Netflix features, and luxury lifestyle campaigns. RED V-Raptor and anamorphic lens master.',
    rating: 4.96,
    reviewCount: 78,
    completedShoots: 125,
    startingPrice: 55000,
    priceUnit: 'per_day',
    location: { city: 'Mumbai / Goa', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 10,
    specialties: ['8K Music Videos', 'Anamorphic Cinema', 'Concert Visuals', 'Drone DPs'],
    equipment: ['RED V-Raptor 8K VV', 'Cooke Anamorphic /i Prime Set', 'DJI Ronin 2 Gimbal', 'Teradek Bolt 4K Wireless Video'],
    portfolio: [
      {
        id: 'port-12',
        title: 'Neon Stage Concert 8K Cinematography',
        category: 'Concert Cinema',
        url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-10',
        title: 'Music Video / Commercial Directing & DP',
        price: 55000,
        pricingType: 'per_day',
        deliveryDays: 14,
        description: 'Complete cinema camera package with master anamorphic lenses, lighting director, and 8K master file.',
        inclusions: ['RED 8K Camera Package', 'Anamorphic Glass', 'Gaffer & Grip Team', 'Full Color Graded Master'],
      },
    ],
  },
  {
    id: 'pro-8',
    name: 'Meera Nambiar',
    role: ROLES.PHOTOGRAPHER,
    category: 'Architectural & Interior Photographer',
    tagline: 'Architectural, Luxury Villa & Hospitality Interior Photographer',
    bio: 'Documenting award-winning architecture, heritage palaces, luxury villas in Goa, and 5-star hotels across India and Southeast Asia. Featured in Architectural Digest.',
    rating: 4.97,
    reviewCount: 110,
    completedShoots: 150,
    startingPrice: 28000,
    priceUnit: 'per_day',
    location: { city: 'Goa / Kochi', state: 'Goa', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 7,
    specialties: ['Luxury Villas', 'Boutique Resorts', 'Interior Staging', 'Twilight Flambient Stills'],
    equipment: ['Canon EOS R5', 'TS-E 17mm f/4L Tilt-Shift', 'TS-E 24mm f/3.5L II', 'CamRanger 2 Wireless Live View'],
    portfolio: [
      {
        id: 'port-13',
        title: 'Twilight Villa in Assagao, Goa',
        category: 'Architecture',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-11',
        title: 'Full Property Architecture & Interior Shoot',
        price: 28000,
        pricingType: 'per_project',
        deliveryDays: 5,
        description: 'Complete interior, exterior, twilight, and detail coverage for hospitality, real estate, and design portfolios.',
        inclusions: ['Day & Twilight Shoots', 'Tilt-Shift Perspective Correction', '25 Magazine-Quality Stills', 'Architectural License'],
      },
    ],
  },
  {
    id: 'pro-9',
    name: 'Zoya Qureshi',
    role: ROLES.EDITOR,
    category: 'High-End Beauty & Skin Retoucher',
    tagline: 'High-End Beauty, Skin Retoucher & Magazine Compositor',
    bio: 'Over 400+ international beauty, cosmetic, and jewelry campaigns retouched for Vogue, Harper’s Bazaar, and cosmetic brands. Non-destructive frequency separation and color grading.',
    rating: 4.99,
    reviewCount: 310,
    completedShoots: 410,
    startingPrice: 16000,
    priceUnit: 'per_project',
    location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 8,
    specialties: ['High-End Skin Retouching', 'Jewelry Polishing', 'Hair Cleanup', 'Color Harmony'],
    equipment: ['Wacom Cintiq Pro 27', 'Capture One Pro 23', 'Adobe Photoshop CC', 'BenQ SW321C Calibrated Monitor'],
    portfolio: [
      {
        id: 'port-14',
        title: 'Natural Texture Skin Retouch for Beauty Brand',
        category: 'Retouching',
        url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-12',
        title: 'Editorial / Beauty High-End Retouch Pack (10 Images)',
        price: 16000,
        pricingType: 'per_project',
        deliveryDays: 3,
        description: 'Pristine pore-preserving frequency separation, dodging & burning, color grading, and print-ready delivery.',
        inclusions: ['10 Magazine-Finish Images', 'Natural Texture Retention', 'Color Matching', 'Unlimited Polish Tweaks'],
      },
    ],
  },
  {
    id: 'pro-10',
    name: 'Tariq Al-Mansoor',
    role: ROLES.VIDEOGRAPHER,
    category: 'Destination Wedding Filmmaker',
    tagline: 'Luxury Destination Wedding Filmmaker & FPV Drone Specialist',
    bio: 'Crafting emotion-rich royal cinema for high-profile weddings across Dubai, Jaipur, Lake Como, and Santorini. Signature cinematic drone master.',
    rating: 4.97,
    reviewCount: 92,
    completedShoots: 110,
    startingPrice: 75000,
    priceUnit: 'per_day',
    location: { city: 'Dubai / Jaipur', state: 'Rajasthan', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 10,
    specialties: ['Destination Royal Weddings', 'FPV Fly-Throughs', 'Teaser Cuts in 24h', 'Sound Design'],
    equipment: ['RED Komodo 6K', 'Custom FPV Cinelifter', 'Sony FX3', 'Leica R Vintage Cinema Primes'],
    portfolio: [
      {
        id: 'port-15',
        title: 'Royal Palace FPV Drone Fly-Through',
        category: 'Weddings',
        url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-13',
        title: 'Luxury Destination Wedding Cinema Package',
        price: 75000,
        pricingType: 'per_day',
        deliveryDays: 14,
        description: 'Elite 3-person film crew with FPV drone, 6K raw capture, sound engineer, and same-week trailer.',
        inclusions: ['3 Master Cinematographers', 'Custom FPV Drone', '24-Hour Social Reel', '25-Min Master Film', 'Raw SSD'],
      },
    ],
  },
  {
    id: 'pro-11',
    name: 'Pooja Bhattacharya',
    role: ROLES.PHOTOGRAPHER,
    category: 'Maternity & Street Documentary',
    tagline: 'Emotive Street Documentary & Fine Art Maternity Portraiture',
    bio: 'Storytelling through natural, unposed, and deeply moving human portraits. Winner of National Geographic India Traveler Photo Award.',
    rating: 4.96,
    reviewCount: 135,
    completedShoots: 175,
    startingPrice: 20000,
    priceUnit: 'per_day',
    location: { city: 'Kolkata / Delhi', state: 'West Bengal', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 6,
    specialties: ['Candid Maternity', 'Street Documentary', 'Family Heritage', 'Natural Light Storytelling'],
    equipment: ['Fujifilm GFX 100 II Medium Format', 'GF 110mm f/2 R LM WR', 'GF 45mm f/2.8 R WR'],
    portfolio: [
      {
        id: 'port-16',
        title: 'Morning Light Along the Hooghly River',
        category: 'Documentary',
        url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-14',
        title: 'Intimate Fine Art Portrait Session',
        price: 20000,
        pricingType: 'fixed',
        deliveryDays: 5,
        description: 'Calm, soulful 3-hour session capturing candid family or personal stories with filmic tones.',
        inclusions: ['3 Hours On-Location', '40 Master Graded High-Res Photos', 'Private Client Gallery', 'Fine Art Prints'],
      },
    ],
  },
  {
    id: 'pro-12',
    name: 'Aditya Singhal',
    role: ROLES.PHOTOGRAPHER,
    category: 'Culinary & Food Styling Specialist',
    tagline: 'Michelin-Grade Culinary, Restaurant & Beverage Styling Photographer',
    bio: 'Photographing for luxury restaurants, cocktail bars, cookbooks, and global F&B brands. Natural organic lighting and steam/splash capture specialist.',
    rating: 4.95,
    reviewCount: 190,
    completedShoots: 230,
    startingPrice: 24000,
    priceUnit: 'per_day',
    location: { city: 'Delhi / Jaipur', state: 'Delhi', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 7,
    specialties: ['Artisanal Food', 'Cocktail Splashes', 'Menu Lookbooks', 'Restaurant Ambience'],
    equipment: ['Nikon Z8', 'Nikkor Z 105mm f/2.8 VR S Macro', 'Profoto B10X Plus', 'Custom Food Styling Kit'],
    portfolio: [
      {
        id: 'port-17',
        title: 'Handmade Saffron Risotto Culinary Shoot',
        category: 'Food',
        url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-15',
        title: 'Restaurant Menu & Hero Dishes Shoot',
        price: 24000,
        pricingType: 'per_day',
        deliveryDays: 4,
        description: 'Complete food and beverage shoot with professional food styling props and macro lighting.',
        inclusions: ['Full Day Shoot', 'Up to 20 Hero Dishes', 'Food Styling On-Set', 'Color Graded Stills for Web & Print'],
      },
    ],
  },
  {
    id: 'pro-13',
    name: 'Sameer Joshi',
    role: ROLES.PHOTOGRAPHER,
    category: 'Concert & Tour Photographer',
    tagline: 'Live Concert, Arena Music Tour & Festival Visual Specialist',
    bio: 'Covering stadium rock shows, Sunburn Festival, Lollapalooza India, and national artist tours. Unmatched low-light high-energy stage capture.',
    rating: 4.97,
    reviewCount: 155,
    completedShoots: 190,
    startingPrice: 30000,
    priceUnit: 'per_day',
    location: { city: 'Mumbai / Bengaluru', state: 'Maharashtra', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 8,
    specialties: ['Arena Concerts', 'DJ Festivals', 'Artist Backstage', 'High-Speed Stage Action'],
    equipment: ['Sony A9 III (Global Shutter)', 'Sony 70-200mm f/2.8 GM II', 'Sony 14mm f/1.8 GM', 'Sound Blimp Enclosure'],
    portfolio: [
      {
        id: 'port-18',
        title: 'Mainstage Festival Night Laser & Crowd Stills',
        category: 'Events',
        url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-16',
        title: 'Festival / Concert Full Live Coverage',
        price: 30000,
        pricingType: 'per_day',
        deliveryDays: 2,
        description: 'High-energy stage stills, backstage candids, crowd shots, and same-night social drop.',
        inclusions: ['Full Event Coverage', '50 Same-Night Selects', '200 Master Edited Action Stills', 'Press License'],
      },
    ],
  },
  {
    id: 'pro-14',
    name: 'Sneha Ganguly',
    role: ROLES.EDITOR,
    category: 'Viral Short-Form & Reel Specialist',
    tagline: 'High-Retention Reels, TikTok & YouTube Shorts Video Editor',
    bio: 'Edited viral short-form campaigns garnering over 150M+ views for top creators, beauty brands, and tech startups. Pacing, sound design, and custom 3D typography.',
    rating: 4.98,
    reviewCount: 380,
    completedShoots: 500,
    startingPrice: 12000,
    priceUnit: 'per_project',
    location: { city: 'Kolkata', state: 'West Bengal', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 5,
    specialties: ['Viral Reels', 'Dynamic Captions', 'Sound Design Effects', 'High-Pacing Transitions'],
    equipment: ['Adobe Premiere Pro & After Effects', 'Soundly SFX Library', 'Apple Studio Display', 'Custom Motion Graphic Packs'],
    portfolio: [
      {
        id: 'port-19',
        title: 'Dynamic Motion Typography Reel Pack',
        category: 'Short Form',
        url: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-17',
        title: 'Viral Instagram Reels Pack (5 Videos)',
        price: 12000,
        pricingType: 'per_project',
        deliveryDays: 2,
        description: '5 high-retention 9:16 vertical videos with bespoke subtitles, SFX, and hook optimization.',
        inclusions: ['5 Vertical Reels', 'Custom Animated Subtitles', 'Licensed SFX & Music', '48-Hour Turnaround'],
      },
    ],
  },
  {
    id: 'pro-15',
    name: 'Ishita Sharma',
    role: ROLES.PHOTOGRAPHER,
    category: 'Astrophotography & Alpine Adventure',
    tagline: 'High-Altitude Celestial & Dark-Sky Milky Way Astrophotographer',
    bio: 'Leading nighttime high-altitude expeditions into Spiti Valley, Ladakh, and Norway. Expert in deep-sky tracking, panoramic star trails, and nocturnal timelapses.',
    rating: 4.99,
    reviewCount: 82,
    completedShoots: 95,
    startingPrice: 34000,
    priceUnit: 'per_day',
    location: { city: 'Ladakh / Spiti Valley', state: 'Himachal Pradesh', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 8,
    specialties: ['Milky Way Panoramas', 'Deep Sky Tracking', 'Nocturnal Timelapses', 'Starry Adventure Portraits'],
    equipment: ['Sony A7S III (Astro-modified)', 'Sigma 14mm f/1.4 DG DN Art', 'Sky-Watcher Star Adventurer Tracker', 'Carbon Tripod Heads'],
    portfolio: [
      {
        id: 'port-20',
        title: 'Milky Way Core Over Key Monastery, Spiti',
        category: 'Astrophotography',
        url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-18',
        title: 'High-Altitude Dark Sky Milky Way Shoot',
        price: 34000,
        pricingType: 'per_project',
        deliveryDays: 7,
        description: 'Nighttime celestial shoot in designated dark sky reserves with deep-sky star tracking.',
        inclusions: ['Night Expedition Guiding', 'Gigapixel Star Panoramas', 'Star Trail Time-Lapse', 'Fine Art 4K Wallpapers'],
      },
    ],
  },
  {
    id: 'pro-16',
    name: 'Farhan Akhtar Studio',
    role: ROLES.VIDEOGRAPHER,
    category: 'Brand Commercial & Narrative Film',
    tagline: 'Brand Commercial, Documentary & Narrative Studio Director',
    bio: 'Full-service production studio delivering high-budget commercials, tech launches, and emotional documentaries. ARRI and Cooke optics standard.',
    rating: 4.98,
    reviewCount: 65,
    completedShoots: 85,
    startingPrice: 65000,
    priceUnit: 'per_project',
    location: { city: 'Hyderabad', state: 'Telangana', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 12,
    specialties: ['Brand Documentaries', 'ARRI Alexa Filming', 'Original Score Production', 'Global Ad Campaigns'],
    equipment: ['ARRI Alexa Mini LF', 'Atlas Orion Anamorphic Set', 'Sound Devices 833 Recorder', 'Astera Titan Tubes'],
    portfolio: [
      {
        id: 'port-21',
        title: 'Heritage Textile Artisan Documentary',
        category: 'Documentary',
        url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-19',
        title: 'Turnkey Commercial Film Production',
        price: 65000,
        pricingType: 'per_project',
        deliveryDays: 20,
        description: 'Complete concept development, scripting, casting, shooting on ARRI, and theatrical sound mix.',
        inclusions: ['Full Film Crew', 'Script & Storyboard', '4K Cinema Delivery', 'Broadcast License', 'Dolby 5.1 Mix'],
      },
    ],
  },
  {
    id: 'pro-17',
    name: 'Karan Malhotra',
    role: ROLES.PHOTOGRAPHER,
    category: 'Corporate Executive & Keynote Specialist',
    tagline: 'Corporate Executive Headshots & Global Keynote Summit Photographer',
    bio: 'Providing Fortune 500 executives, Forbes 30 Under 30 founders, and tech leadership with commanding, confidence-inspiring portraiture.',
    rating: 4.95,
    reviewCount: 220,
    completedShoots: 310,
    startingPrice: 26000,
    priceUnit: 'per_day',
    location: { city: 'Gurugram / Delhi NCR', state: 'Haryana', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 9,
    specialties: ['CEO Headshots', 'Summit Keynotes', 'Annual Reports', 'On-Site Mobile Studio'],
    equipment: ['Nikon Z9', 'Profoto D2 AirTTL 1000W', 'Elinchrom Rotalux Softboxes', 'Tether Tools Pro Table'],
    portfolio: [
      {
        id: 'port-22',
        title: 'Global Tech Leadership Summit Keynote',
        category: 'Corporate',
        url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-20',
        title: 'Executive Headshot Mobile Studio Day',
        price: 26000,
        pricingType: 'per_day',
        deliveryDays: 3,
        description: 'Mobile studio set up inside your corporate headquarters for up to 25 executive headshots with live selection.',
        inclusions: ['On-Site Studio Lighting', 'Instant iPad Proofing', '25 Retouched Headshots', 'Full Corporate Usage Rights'],
      },
    ],
  },
  {
    id: 'pro-18',
    name: 'Maya Chandran',
    role: ROLES.PHOTOGRAPHER,
    category: 'Contemporary Dance & Performance Arts',
    tagline: 'Classical Bharatnatyam, Contemporary Dance & Theater Photographer',
    bio: 'Freezing dynamic human motion, silk fabric fluidity, and dramatic stage lighting for classical dancers and international theater troupes.',
    rating: 4.97,
    reviewCount: 120,
    completedShoots: 145,
    startingPrice: 22000,
    priceUnit: 'per_day',
    location: { city: 'Bengaluru / Chennai', state: 'Karnataka', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 6,
    specialties: ['Dance Motion Freeze', 'Stage Chiaroscuro', 'Performance Arangetram', 'Costume Details'],
    equipment: ['Leica SL2-S', 'Leica Vario-Elmarit-SL 24-90mm', 'Godox High-Speed Sync Flashes'],
    portfolio: [
      {
        id: 'port-23',
        title: 'Dramatic Stage Bharatnatyam Leap',
        category: 'Performance',
        url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-21',
        title: 'Performance Arangetram & Stage Shoot',
        price: 22000,
        pricingType: 'per_project',
        deliveryDays: 5,
        description: 'Full stage performance coverage plus dedicated pre-show costume and mudra portraiture.',
        inclusions: ['Pre-Performance Portraits', 'Live Stage High-Speed Capture', '150 High-Res Edited Stills', 'Web Album'],
      },
    ],
  },
  {
    id: 'pro-19',
    name: 'Rahul Vohra',
    role: ROLES.PHOTOGRAPHER,
    category: 'E-Commerce Fashion & Catalog Specialist',
    tagline: 'High-Volume E-Commerce Fashion Lookbook & Ghost Mannequin Specialist',
    bio: 'Operating high-throughput commercial studios for leading Amazon, Myntra, and Nykaa sellers with fast 48-hour turnarounds.',
    rating: 4.93,
    reviewCount: 290,
    completedShoots: 380,
    startingPrice: 15000,
    priceUnit: 'per_day',
    location: { city: 'Jaipur / Surat', state: 'Rajasthan', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: false,
    experienceYears: 7,
    specialties: ['E-Commerce Catalogs', 'Ghost Mannequins', 'Model Studio Lookbooks', 'High-Volume Turnaround'],
    equipment: ['Sony A7C II', 'Godox Studio Strobes', 'Automated Background Cutout Suite'],
    portfolio: [
      {
        id: 'port-24',
        title: 'High-Volume E-Commerce Fashion Catalog',
        category: 'E-Commerce',
        url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-22',
        title: 'Full Day Catalog Studio Shoot (Up to 30 Garments)',
        price: 15000,
        pricingType: 'per_day',
        deliveryDays: 2,
        description: 'Complete studio model shoot with white background clipping, color accuracy, and e-commerce sizing.',
        inclusions: ['Model Studio Setup', '30 Apparel Looks (Front/Back/Detail)', 'Pure White Cutout PNGs', '48-Hour Delivery'],
      },
    ],
  },
  {
    id: 'pro-20',
    name: 'Siddharth Roy',
    role: ROLES.EDITOR,
    category: 'CGI & Virtual Production Artist',
    tagline: 'Unreal Engine 5 Virtual Production & 3D Environment Compositor',
    bio: 'Merging live camera footage with photorealistic 3D Unreal Engine environments for film and futuristic commercial spots.',
    rating: 4.99,
    reviewCount: 110,
    completedShoots: 130,
    startingPrice: 40000,
    priceUnit: 'per_project',
    location: { city: 'Bengaluru / Mumbai', state: 'Karnataka', country: 'India' },
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    isVerified: true,
    isFeatured: true,
    experienceYears: 8,
    specialties: ['Unreal Engine 5', 'Virtual Sets', 'VFX Compositing', '3D Camera Tracking'],
    equipment: ['Dual NVIDIA RTX 4090 Workstation', 'DaVinci Resolve Studio & Fusion', 'OptiTrack Motion Capture'],
    portfolio: [
      {
        id: 'port-25',
        title: 'Futuristic Sci-Fi Virtual Environment Composite',
        category: 'VFX',
        url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
        mediaType: 'image',
      },
    ],
    services: [
      {
        id: 'srv-23',
        title: '3D Virtual Environment Film Compositing',
        price: 40000,
        pricingType: 'per_project',
        deliveryDays: 10,
        description: 'Bespoke photorealistic 3D environment integrated with live green screen or tracked studio footage.',
        inclusions: ['Unreal Engine 5 Scene Asset', '3D Camera Track & Matchmove', '4K Final Composite', 'Color Integration'],
      },
    ],
  },
];

export const MOCK_REVIEWS = [
  {
    id: 'rev-1',
    professionalId: 'pro-1',
    user: {
      name: 'Rhea & Devansh Kapoor',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    },
    rating: 5,
    event: 'Royal Wedding in Jagmandir, Udaipur',
    date: 'February 2026',
    comment:
      'Booking Aarav through LensCraft was the single best decision of our wedding. The subtle emotional frames and royal palace lighting he captured made our parents weep tears of joy.',
  },
  {
    id: 'rev-2',
    professionalId: 'pro-3',
    user: {
      name: 'Sameer Verma (Creative Director, Vayu)',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    rating: 5,
    event: 'Luxury Haute Couture Lookbook',
    date: 'January 2026',
    comment:
      'Nisha’s eye for silhouette and medium-format Hasselblad clarity delivered a campaign that got picked up across top fashion glossies. Seamless escrow booking and instant delivery.',
  },
  {
    id: 'rev-3',
    professionalId: 'pro-2',
    user: {
      name: 'Dr. Priya & Tanmay Nambiar',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    },
    rating: 5,
    event: 'Destination Wedding Film in Goa',
    date: 'March 2026',
    comment:
      'Kabir’s FX6 cinema camera work and drone fly-throughs look like a high-budget Netflix film. We have rewatched our wedding teaser at least 50 times already.',
  },
  {
    id: 'rev-4',
    professionalId: 'pro-4',
    user: {
      name: 'Anandita Roy (Indie Filmmaker)',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    },
    rating: 5,
    event: 'Documentary Short Film Color Grade',
    date: 'February 2026',
    comment:
      'Devansh is an absolute master in DaVinci Resolve. He elevated our raw camera logs into a rich 35mm film print emulation that won best cinematography at film festivals.',
  },
  {
    id: 'rev-5',
    professionalId: 'pro-9',
    user: {
      name: 'Meenakshi Sundaram (Cosmetics Head)',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    },
    rating: 5,
    event: 'International Beauty Retouch Campaign',
    date: 'March 2026',
    comment:
      'Zoya preserved genuine human skin pores while delivering magazine-finish radiance. Her speed and pixel-level precision on 100-megapixel files are unrivaled.',
  },
];
